### ISSUE TITLE
example fine-tuning (separate init and call; selection of no. of threads)

### ISSUE THREAD

**Issue by slayoo** [fynv/CURandRTC#1]
Two questions concerning the presented examples:
- how can one separate initialisation and execution into separate Python calls?
- what would be a robust way of figureing out sensible launch parameters (no. of threads, instead of hardcoded 32 as in the example)?

**Comment by slayoo** [comment]
and big thanks for opening up the RTC APIs to Python users!

**Comment by slayoo** [comment]
ping :)

**Comment by slayoo** [comment]
@fynv To rephrase the question: how to mimic the following Thrust+CURAND hellow world with CURandRTC?

```C++
# include <curand.h>

...

curandGenerator_t gen;
int status = curandCreateGenerator(&gen, CURAND_RNG_PSEUDO_MTGP32);

...

void generate_n(thrust_device::vector<float> &v, const thrust_size_t n) {
	  int status = curandGenerateUniform(gen, thrust::raw_pointer_cast(v.data()), n);
}
```

Thanks for help!
Sylwester

**Comment by fynv** [comment]
Hi slayoo, so sorry I missed this question. Once missed it, there's little chance to be aware of its existance later..

To separate init and call, you basically need a DVVector of "RNGState"s:

```python
import ThrustRTC as trtc
import CURandRTC as rndrtc

rng = rndrtc.DVRNG()

ker_init = trtc.For(['rng','states'], 'idx',
	'''
	rng.state_init(1234, idx, 0, states[idx]);
	''')

ker_call = trtc.For(['states', 'vec_rnd'], 'idx',
	'''
	vec_rnd[idx]=(float)states[idx].rand01();
	'''
	)

rng_states = trtc.device_vector('RNGState', 1024)
d_vec_rnd = trtc.device_vector('float', 1024)

ker_init.launch_n(1024, [rng, rng_states])
ker_call.launch_n(1024, [rng_states, d_vec_rnd])
print (d_vec_rnd.to_host())
```
This doesn't look so nice as it is in Thrust+CURAND. However, I believe the underlying calculation is similar. You basically need a separate rng-state for each independent thread, or you have to serialized the random number generation.

* what would be a robust way of figureing out sensible launch parameters (no. of threads, instead of hardcoded 32 as in the example)?

The "32" in the example is not about performance, it is just to show that an rng-state can be reused within a thread. 

Btw, for deciding the size of a thread block, 'class Kernel' has the methods: 
* calc_optimal_block_size(): calculate the optimal size of a thread block
* calc_number_blocks(): caculate the minimal number of blocks to keep the SMs busy.
These are based on the CUDA occupancy APIs.

If you use 'class For' instead, then calc_optimal_block_size() is done internally.

**Comment by fynv** [comment]
Just modified the samples to make it clear. Actually, this repo only implemented a very small subset of CURAND.

**Comment by slayoo** [comment]
Thank you!

Is the (float) cast intentional/needed in the code?

**Comment by fynv** [comment]
>> Is the (float) cast intentional/needed in the code?
rand01() returns double, vec_rnd[idx] is a float as we pass it in, so the cast makes sense ( but not important).

**Comment by slayoo** [comment]
Thank you for all the clarifications!
